ccflags-y += -DWLAN_DUMP_DATA
obj-$(CONFIG_SC2331) += sprdwl.o
sprdwl-objs:= wlan_core.o wlan_fifo.o wlan_msg_q.o wlan_cmd.o wlan_npi.o wlan_hostapd_conf.o wlan_cfg80211.o wlan_wapi.o  wlan_tcp.o wlan_qos.o $(sprdwl-y)

